version: '3.8'

services:
  # Serviço do Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres
    networks:
      - app-network

  # Banco de dados para o Keycloak
  postgres:
    image: postgres:14
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Serviço NestJS
  # nestjs-app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   container_name: nestjs-app
  #   environment:
  #     - NODE_ENV=development
  #     - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
  #     - KEYCLOAK_REALM=meu-realm
  #     - KEYCLOAK_CLIENT_ID=meu-cliente
  #     - KEYCLOAK_SECRET=meu-segredo
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./app:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - keycloak
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: